import path from 'node:path';

import { migrate } from 'drizzle-orm/node-postgres/migrator';

import type { Db } from './client';

/** SQL migrations generated by drizzle-kit live in backend/drizzle (override with MIGRATIONS_DIR). */
export function migrationsDir(): string {
  return process.env.MIGRATIONS_DIR ?? path.resolve(process.cwd(), 'drizzle');
}

export async function runMigrations(db: Db): Promise<void> {
  await migrate(db, { migrationsFolder: migrationsDir() });
}
