import type { AvoidFood, Diet, MealType, Nutrients } from '../../../shared/api';

/**
 * Curated meal ideas: the fallback when Claude is off, fails or returns a recipe
 * that breaks the user's preferences. Common Latvian-shop ingredients, ≤ 40 min,
 * realistic per-serving values (rounded, from standard food tables).
 *
 * `diets` lists the restricted diets a recipe fits ('any' always fits);
 * `contains` lists the avoid-groups it contains. test/recipes.test.ts checks that
 * both agree with the keyword blacklist in recipes.ts.
 */

export interface CuratedRecipe {
  key: string;
  title: string;
  minutes: number;
  servings: number;
  servingGrams: number;
  mealTypes: MealType[];
  diets: Exclude<Diet, 'any'>[];
  contains: AvoidFood[];
  ingredients: { name: string; amount: string }[];
  steps: string[];
  perServing: Nutrients;
  tags: string[];
}

const n = (kcal: number, proteinG: number, carbsG: number, fatG: number, fibreG: number): Nutrients => ({ kcal, proteinG, carbsG, fatG, fibreG });

export const CURATED_RECIPES: CuratedRecipe[] = [
  {
    key: 'biezpiens-ogas',
    title: 'Biezpiens ar ogām un linsēklām',
    minutes: 5,
    servings: 1,
    servingGrams: 330,
    mealTypes: ['breakfast', 'snack'],
    diets: ['vegetarian', 'pescatarian'],
    contains: ['lactose'],
    ingredients: [
      { name: 'Biezpiens, 5 %', amount: '200 g' },
      { name: 'Saldētas ogas', amount: '100 g' },
      { name: 'Maltas linsēklas', amount: '1 ēd. k.' },
      { name: 'Medus', amount: '1 tējk.' },
    ],
    steps: ['Atkausē ogas mikroviļņu krāsnī vai ņem svaigas.', 'Samaisi biezpienu ar ogām, pārkaisi linsēklas un pārlej medu.'],
    perServing: n(330, 32, 24, 12, 5),
    tags: ['5 min', 'veģetārs', 'bez glutēna'],
  },
  {
    key: 'auzu-putra-abols',
    title: 'Auzu putra ar ābolu un valriekstiem',
    minutes: 10,
    servings: 1,
    servingGrams: 350,
    mealTypes: ['breakfast'],
    diets: ['vegetarian', 'vegan', 'pescatarian'],
    contains: ['gluten', 'nuts'],
    ingredients: [
      { name: 'Auzu pārslas', amount: '60 g' },
      { name: 'Auzu dzēriens', amount: '250 ml' },
      { name: 'Ābols', amount: '1 gab.' },
      { name: 'Valrieksti', amount: '15 g' },
      { name: 'Kanēlis', amount: 'šķipsniņa' },
    ],
    steps: ['Vāri pārslas auzu dzērienā 5 minūtes, maisot.', 'Pievieno sagrieztu ābolu un kanēli, pārkaisi valriekstus.'],
    perServing: n(430, 11, 62, 15, 9),
    tags: ['10 min', 'vegāns'],
  },
  {
    key: 'omlete-spinati',
    title: 'Omlete ar spinātiem un fetu',
    minutes: 15,
    servings: 1,
    servingGrams: 250,
    mealTypes: ['breakfast', 'dinner'],
    diets: ['vegetarian', 'pescatarian'],
    contains: ['eggs', 'lactose'],
    ingredients: [
      { name: 'Olas', amount: '3 gab.' },
      { name: 'Spināti', amount: '60 g' },
      { name: 'Feta siers', amount: '30 g' },
      { name: 'Tomāts', amount: '1 gab.' },
      { name: 'Olīveļļa', amount: '1 tējk.' },
    ],
    steps: ['Saputo olas ar šķipsniņu sāls.', 'Pannā eļļā apcep spinātus 1 minūti, pārlej olas un cep uz lēnas uguns.', 'Pārkaisi sadrupinātu fetu, pasniedz ar tomātu.'],
    perServing: n(390, 26, 7, 28, 2),
    tags: ['15 min', 'veģetārs', 'bez glutēna'],
  },
  {
    key: 'tofu-kultenis',
    title: 'Tofu kultenis ar dārzeņiem',
    minutes: 15,
    servings: 1,
    servingGrams: 300,
    mealTypes: ['breakfast', 'dinner'],
    diets: ['vegetarian', 'vegan', 'pescatarian'],
    contains: [],
    ingredients: [
      { name: 'Tofu', amount: '180 g' },
      { name: 'Paprika', amount: '1 gab.' },
      { name: 'Sīpols', amount: '½ gab.' },
      { name: 'Kurkuma', amount: '½ tējk.' },
      { name: 'Rapšu eļļa', amount: '1 tējk.' },
    ],
    steps: ['Apcep sīpolu un papriku eļļā 3 minūtes.', 'Pievieno sadrupinātu tofu un kurkumu, cep vēl 5 minūtes.'],
    perServing: n(330, 24, 13, 20, 5),
    tags: ['15 min', 'vegāns', 'bez glutēna'],
  },
  {
    key: 'lecu-zupa',
    title: 'Sarkano lēcu zupa ar burkāniem',
    minutes: 30,
    servings: 3,
    servingGrams: 400,
    mealTypes: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'pescatarian'],
    contains: [],
    ingredients: [
      { name: 'Sarkanās lēcas', amount: '200 g' },
      { name: 'Burkāni', amount: '2 gab.' },
      { name: 'Sīpols', amount: '1 gab.' },
      { name: 'Tomātu pasta', amount: '2 ēd. k.' },
      { name: 'Dārzeņu buljons', amount: '1 l' },
    ],
    steps: ['Apcep sīpolu, pievieno rīvētus burkānus un tomātu pastu.', 'Pievieno lēcas un buljonu, vāri 20 minūtes.', 'Sablendē daļu zupas biezākai konsistencei.'],
    perServing: n(310, 19, 50, 3, 12),
    tags: ['30 min', 'vegāns', 'bez glutēna'],
  },
  {
    key: 'griki-vista',
    title: 'Griķi ar vistas fileju un gurķu salātiem',
    minutes: 25,
    servings: 2,
    servingGrams: 420,
    mealTypes: ['lunch', 'dinner'],
    diets: [],
    contains: [],
    ingredients: [
      { name: 'Griķi', amount: '140 g' },
      { name: 'Vistas fileja', amount: '300 g' },
      { name: 'Gurķi', amount: '2 gab.' },
      { name: 'Dilles', amount: 'sauja' },
      { name: 'Rapšu eļļa', amount: '1 ēd. k.' },
    ],
    steps: ['Vāri griķus 15 minūtes.', 'Sagriez fileju strēmelēs un apcep eļļā 8–10 minūtes.', 'Sagriez gurķus ar dillēm, pasniedz kopā.'],
    perServing: n(520, 44, 55, 12, 7),
    tags: ['25 min', 'bez glutēna', 'bez laktozes'],
  },
  {
    key: 'lasis-kartupeli',
    title: 'Cepts lasis ar kartupeļiem un brokoļiem',
    minutes: 35,
    servings: 2,
    servingGrams: 430,
    mealTypes: ['lunch', 'dinner'],
    diets: ['pescatarian'],
    contains: ['fish'],
    ingredients: [
      { name: 'Laša fileja', amount: '260 g' },
      { name: 'Kartupeļi', amount: '400 g' },
      { name: 'Brokoļi', amount: '300 g' },
      { name: 'Citrons', amount: '½ gab.' },
      { name: 'Olīveļļa', amount: '1 ēd. k.' },
    ],
    steps: ['Cep kartupeļu daiviņas 200 °C 15 minūtes.', 'Pievieno lasi un brokoļus, apslaki ar eļļu un cep vēl 15 minūtes.', 'Pasniedz ar citrona sulu.'],
    perServing: n(560, 34, 45, 25, 8),
    tags: ['35 min', 'ar zivi', 'bez glutēna'],
  },
  {
    key: 'aunazirnu-sautejums',
    title: 'Aunazirņu un dārzeņu sautējums ar rīsiem',
    minutes: 30,
    servings: 2,
    servingGrams: 450,
    mealTypes: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'pescatarian'],
    contains: [],
    ingredients: [
      { name: 'Aunazirņi, konservēti', amount: '400 g' },
      { name: 'Rīsi', amount: '120 g' },
      { name: 'Tomāti, konservēti', amount: '400 g' },
      { name: 'Cukini', amount: '1 gab.' },
      { name: 'Ķiploks', amount: '2 daiviņas' },
    ],
    steps: ['Vāri rīsus.', 'Apcep ķiploku un sagrieztu cukini, pievieno tomātus un noskalotus aunazirņus.', 'Sautē 15 minūtes, pasniedz ar rīsiem.'],
    perServing: n(500, 19, 85, 7, 15),
    tags: ['30 min', 'vegāns', 'bez glutēna'],
  },
  {
    key: 'pupinu-salati',
    title: 'Pupiņu un kukurūzas salāti ar avokado',
    minutes: 15,
    servings: 2,
    servingGrams: 320,
    mealTypes: ['lunch', 'dinner', 'snack'],
    diets: ['vegetarian', 'vegan', 'pescatarian'],
    contains: [],
    ingredients: [
      { name: 'Sarkanās pupiņas, konservētas', amount: '400 g' },
      { name: 'Kukurūza, konservēta', amount: '150 g' },
      { name: 'Avokado', amount: '1 gab.' },
      { name: 'Paprika', amount: '1 gab.' },
      { name: 'Laima', amount: '1 gab.' },
    ],
    steps: ['Noskalo pupiņas un kukurūzu.', 'Sagriez avokado un papriku, samaisi visu ar laimas sulu un šķipsniņu sāls.'],
    perServing: n(430, 16, 50, 16, 16),
    tags: ['15 min', 'vegāns', 'bez glutēna'],
  },
  {
    key: 'titars-darzeni',
    title: 'Tītara fileja ar ceptiem dārzeņiem',
    minutes: 35,
    servings: 2,
    servingGrams: 400,
    mealTypes: ['lunch', 'dinner'],
    diets: [],
    contains: [],
    ingredients: [
      { name: 'Tītara fileja', amount: '300 g' },
      { name: 'Ķirbis vai burkāni', amount: '300 g' },
      { name: 'Sarkanais sīpols', amount: '1 gab.' },
      { name: 'Paprika', amount: '1 gab.' },
      { name: 'Olīveļļa', amount: '1 ēd. k.' },
    ],
    steps: ['Sagriez dārzeņus, apslaki ar eļļu un cep 200 °C 15 minūtes.', 'Pievieno tītara gabaliņus un cep vēl 15 minūtes.'],
    perServing: n(420, 40, 28, 15, 7),
    tags: ['35 min', 'bez glutēna', 'bez laktozes'],
  },
  {
    key: 'menca-zirni',
    title: 'Mencas fileja ar zirnīšu biezeni',
    minutes: 25,
    servings: 2,
    servingGrams: 380,
    mealTypes: ['lunch', 'dinner'],
    diets: ['pescatarian'],
    contains: ['fish'],
    ingredients: [
      { name: 'Mencas fileja', amount: '320 g' },
      { name: 'Zaļie zirnīši, saldēti', amount: '300 g' },
      { name: 'Kartupeļi', amount: '200 g' },
      { name: 'Olīveļļa', amount: '1 ēd. k.' },
      { name: 'Citrons', amount: '½ gab.' },
    ],
    steps: ['Vāri kartupeļus un zirnīšus, sablendē ar eļļu.', 'Cep mencu pannā 3–4 minūtes no katras puses.', 'Pasniedz ar citrona sulu.'],
    perServing: n(410, 38, 36, 9, 10),
    tags: ['25 min', 'ar zivi', 'bez glutēna'],
  },
  {
    key: 'rupjmaize-biezpiens',
    title: 'Rupjmaize ar biezpiena krēmu un redīsiem',
    minutes: 10,
    servings: 1,
    servingGrams: 220,
    mealTypes: ['breakfast', 'snack'],
    diets: ['vegetarian', 'pescatarian'],
    contains: ['lactose', 'gluten'],
    ingredients: [
      { name: 'Rupjmaize', amount: '2 šķēles' },
      { name: 'Biezpiens', amount: '100 g' },
      { name: 'Skābais krējums', amount: '1 ēd. k.' },
      { name: 'Redīsi', amount: '4 gab.' },
      { name: 'Loki', amount: 'sauja' },
    ],
    steps: ['Samaisi biezpienu ar krējumu un sagrieztiem lokiem.', 'Uzziedi uz maizes un uzliec redīsu ripiņas.'],
    perServing: n(300, 18, 36, 8, 7),
    tags: ['10 min', 'veģetārs'],
  },
  {
    key: 'humuss-darzeni',
    title: 'Humuss ar dārzeņu salmiņiem un rupjmaizi',
    minutes: 10,
    servings: 1,
    servingGrams: 250,
    mealTypes: ['snack', 'lunch'],
    diets: ['vegetarian', 'vegan', 'pescatarian'],
    contains: ['gluten'],
    ingredients: [
      { name: 'Humuss', amount: '80 g' },
      { name: 'Burkāns', amount: '1 gab.' },
      { name: 'Gurķis', amount: '½ gab.' },
      { name: 'Rupjmaize', amount: '1 šķēle' },
    ],
    steps: ['Sagriez dārzeņus salmiņos.', 'Pasniedz ar humusu un rupjmaizi.'],
    perServing: n(300, 11, 34, 13, 10),
    tags: ['10 min', 'vegāns'],
  },
  {
    key: 'olas-tomati',
    title: 'Vārītas olas ar tomātiem un rupjmaizi',
    minutes: 12,
    servings: 1,
    servingGrams: 260,
    mealTypes: ['breakfast', 'snack'],
    diets: ['vegetarian', 'pescatarian'],
    contains: ['eggs', 'gluten'],
    ingredients: [
      { name: 'Olas', amount: '2 gab.' },
      { name: 'Tomāti', amount: '2 gab.' },
      { name: 'Rupjmaize', amount: '1 šķēle' },
    ],
    steps: ['Vāri olas 8 minūtes.', 'Pasniedz ar tomātiem un rupjmaizi.'],
    perServing: n(310, 17, 26, 14, 6),
    tags: ['12 min', 'veģetārs', 'bez laktozes'],
  },
  {
    key: 'sojas-jogurts',
    title: 'Sojas jogurts ar ogām un ķirbju sēklām',
    minutes: 5,
    servings: 1,
    servingGrams: 270,
    mealTypes: ['breakfast', 'snack'],
    diets: ['vegetarian', 'vegan', 'pescatarian'],
    contains: [],
    ingredients: [
      { name: 'Sojas jogurts', amount: '200 g' },
      { name: 'Ogas', amount: '80 g' },
      { name: 'Ķirbju sēklas', amount: '20 g' },
    ],
    steps: ['Liec jogurtu bļodā, pievieno ogas un pārkaisi ķirbju sēklas.'],
    perServing: n(260, 14, 20, 13, 6),
    tags: ['5 min', 'vegāns', 'bez glutēna'],
  },
  {
    key: 'aunazirnu-uzkoda',
    title: 'Grauzdēti aunazirņi ar paprikas salmiņiem',
    minutes: 25,
    servings: 2,
    servingGrams: 180,
    mealTypes: ['snack'],
    diets: ['vegetarian', 'vegan', 'pescatarian'],
    contains: [],
    ingredients: [
      { name: 'Aunazirņi, konservēti', amount: '400 g' },
      { name: 'Paprika', amount: '1 gab.' },
      { name: 'Kūpināta paprika (garšviela)', amount: '1 tējk.' },
      { name: 'Olīveļļa', amount: '1 tējk.' },
    ],
    steps: ['Noskalo un nosusini aunazirņus, samaisi ar eļļu un garšvielu.', 'Cep 200 °C 20 minūtes, pasniedz ar paprikas salmiņiem.'],
    perServing: n(230, 10, 30, 7, 9),
    tags: ['25 min', 'vegāns', 'bez glutēna'],
  },
  {
    key: 'cukgala-kaposti',
    title: 'Cūkgaļas fileja ar kāpostu salātiem un kartupeļiem',
    minutes: 30,
    servings: 2,
    servingGrams: 430,
    mealTypes: ['lunch', 'dinner'],
    diets: [],
    contains: ['pork'],
    ingredients: [
      { name: 'Cūkgaļas fileja', amount: '300 g' },
      { name: 'Kartupeļi', amount: '400 g' },
      { name: 'Svaigi kāposti', amount: '250 g' },
      { name: 'Burkāns', amount: '1 gab.' },
      { name: 'Rapšu eļļa', amount: '1 ēd. k.' },
    ],
    steps: ['Vāri kartupeļus.', 'Apcep filejas šķēles 4 minūtes no katras puses.', 'Sarīvē kāpostus ar burkānu, pievieno eļļu un sāli.'],
    perServing: n(530, 38, 42, 21, 8),
    tags: ['30 min', 'bez glutēna', 'bez laktozes'],
  },
];
